### ISSUE TITLE
for download subtitle only Crunchyroll use yt-dlp

### ISSUE THREAD

**Issue by decade7117** [Akamaru/issues#1]
If someone want to download just the subtitles, I created a .bat file to do this.

@echo off
:loop
set /p url="Bitte gib die Crunchyroll-URL ein (oder 'exit' zum Beenden): "
if "%url%"=="exit" goto :eof
set flags=--allow-u --write-sub --sub-lang de-DE,en-US --sub-format "ass" -u "EMAIL" -p "PASSWORD" --skip-download
cd /d "FULL PATH TO DESTINATION"
yt-dlp %flags% %url%
goto :loop

i got ERROR: [crunchyroll] GWDU82DQ3: Request blocked by Cloudflare; navigate to Crunchyroll in your browser, then pass the fresh cookies (with --cookies-from-browser or --cookies) and your browser's User-Agent (with --user-agent) i use this command yt-dlp --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36" --cookies "C:/" --write-sub --sub-format "srt" --sub-langs "us" -o "C:/" https://www.crunchyroll.com/watch/GEVUZ7MWK/deer-meets-darkness-girl

**Comment by Akamaru** [comment]
The issue you're describing doesn't seem to be related to my projects. It would be best to reach out to yt-dlp for further assistance, as the problem likely falls within their scope.
